name: PR Title Warning for feat( when v2.0 Exists

on:
  pull_request:
    types: [opened, edited]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # Needed to post a comment on PR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure we fetch all tags

      - name: Check if v2.0 or 2.0 tag exists
        id: check_tag
        run: |
          if git tag | grep -E '^v?2\.0$' >/dev/null 2>&1; then
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
          else
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Check PR Title
        id: title_check
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          if [[ "$PR_TITLE" =~ ^feat\( ]] && [[ "$TAG_EXISTS" == "true" ]]; then
            echo "WARNING: PR title starts with 'feat(' but repo has a v2.0 or 2.0 tag!"
            echo "SHOULD_WARN=true" >> $GITHUB_ENV
          else
            echo "SHOULD_WARN=false" >> $GITHUB_ENV
          fi

      - name: Post Warning Comment on PR
        if: env.SHOULD_WARN == 'true'
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          REPO="${{ github.repository }}"
          COMMENT_BODY="⚠️ **Warning:** Your PR title starts with \`feat(\`, but the repository has a **v2.0** tag. Please follow semantic versioning rules."
          gh api repos/$REPO/issues/$PR_NUMBER/comments -f body="$COMMENT_BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
