name: PR Title Checks

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # Needed to post a comment on PR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure we fetch all tags

      - name: Check if v2.0 or 2.0 tag exists
        id: check_tag
        run: |
          if git tag | grep -E '^v?2\.0$' >/dev/null 2>&1; then
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
          else
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Check PR Title Rules
        id: title_check
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          SHOULD_WARN=false

          # Rule 1: If repo has v2.0 tag, warn if PR title starts with 'feat('
          if [[ "$TAG_EXISTS" == "true" && "$PR_TITLE" =~ ^feat\( ]]; then
            echo "WARNING: PR title starts with 'feat(' but repo has a v2.0 or 2.0 tag!"
            SHOULD_WARN=true
          fi

          # Rule 2: If base branch is 'main', PR title should start with 'patch-1.x.x'
          if [[ "$BASE_BRANCH" == "main" && ! "$PR_TITLE" =~ ^patch-1\.[0-9]+\.[0-9]+ ]]; then
            echo "WARNING: PR targets 'main' but does not start with 'patch-1.x.x'."
            SHOULD_WARN=true
          fi

          echo "SHOULD_WARN=$SHOULD_WARN" >> $GITHUB_ENV

      - name: Post Warning Comment on PR
        if: env.SHOULD_WARN == 'true'
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          REPO="${{ github.repository }}"
          COMMENT_BODY="тЪая╕П **Warning:** Your PR title does not follow the required format.\n\n"

          if [[ "$TAG_EXISTS" == "true" && "$PR_TITLE" =~ ^feat\( ]]; then
            COMMENT_BODY+="ЁЯЪл PR title starts with \`feat(\` but the repo has a **v2.0** tag. Follow semantic versioning.\n"
          fi

          if [[ "$BASE_BRANCH" == "main" && ! "$PR_TITLE" =~ ^patch-1\.[0-9]+\.[0-9]+ ]]; then
            COMMENT_BODY+="ЁЯЪл PR targets \`main\`, but title should start with \`patch-1.x.x\`.\n"
          fi

          gh api repos/$REPO/issues/$PR_NUMBER/comments -f body="$COMMENT_BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
