name: PR Title Checks

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # Needed to post a comment on PR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure we fetch all tags

      - name: Find Branches Starting with 'patch-1.'
        id: find_patch_branches
        run: |
          git fetch --all
          PATCH_BRANCHES=$(git branch -r | grep 'patch-1\.' || echo "None")
          echo "Found branches: $PATCH_BRANCHES"
          echo "PATCH_BRANCHES=$PATCH_BRANCHES" >> $GITHUB_ENV

      - name: Check if v2.0 or 2.0 tag exists
        id: check_tag
        run: |
          if git tag | grep -E '^v?2\.0$' >/dev/null 2>&1; then
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
          else
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Check PR Title Rules
        id: title_check
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          SHOULD_WARN_TITLE=false
          SHOULD_WARN_BRANCH=false

          # Rule 1: If repo has v2.0 tag, warn if PR title starts with 'feat('
          if [[ "$TAG_EXISTS" == "true" && "$PR_TITLE" =~ ^feat\( ]]; then
            echo "WARNING: PR title starts with 'feat(' but repo has a v2.0 or 2.0 tag!"
            SHOULD_WARN_TITLE=true
          fi

          # Rule 2: If repo has v2.0 tag, warn if base branch is 'main'
          if [[ "$TAG_EXISTS" == "true" && "$BASE_BRANCH" == "main" ]]; then
            echo "WARNING: PR targets 'main' but repo has a branch 'patch-1.x.x'."
            SHOULD_WARN_BRANCH=true
          fi

          echo "SHOULD_WARN_TITLE=$SHOULD_WARN_TITLE" >> $GITHUB_ENV
          echo "SHOULD_WARN_BRANCH=$SHOULD_WARN_BRANCH" >> $GITHUB_ENV

      - name: Post Warning Comment on PR
        if: env.SHOULD_WARN_TITLE == 'true' || env.SHOULD_WARN_BRANCH == 'true'
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          REPO="${{ github.repository }}"
          COMMENT_BODY="⚠️ **Warning:** Your PR does not follow the Branching Model requirements for v2.0 upgrade.%0A"

          if [[ "$SHOULD_WARN_TITLE" == "true" ]]; then
            COMMENT_BODY+="PR title starts with \`feat(\` but the repo has a **v2.0** tag. Follow semantic versioning.%0A"
          fi

          if [[ "$SHOULD_WARN_BRANCH" == "true" ]]; then
            COMMENT_BODY+="* PR targets \`main\`, but title should start with \`patch-1.x.x\`.%0A%0A"
            COMMENT_BODY+="**Available Patch Branches:**\n\`${{ env.PATCH_BRANCHES }}\`"
          fi

          gh api repos/$REPO/issues/$PR_NUMBER/comments -f body="$COMMENT_BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
